### ISSUE TITLE
Decide on language server binary distribution

### ISSUE THREAD

**Issue by edusporto** [HigherOrderCO/bend-language-server#3]
The language server (LS) for Bend is currently written in Rust using the relevant libraries `tower-lsp`, `tokio`, and `tree-sitter`. We have now reached a stage we would like to publish the language server as an extension to VSCode, but this raises a technical challenge - how are we going to distribute the language server binary to users of the extension?

We have thought of four solutions, ranked by how desirable they would be to the team.

1. **Compile the LS to WebAssembly (WASM) and embed it into the VSCode extension**
  - Pros:
    1. Distribution is extremely easy
    2. Updating the LS is easy as simply an update to the extension
    3. Does not require users to install the Rust toolchain
  - Cons:
    1. Compiling to WASM is not straight-forward. `tokio`, which we currently use and could change, does have support for WASM, but it is a bit bare-bones and is missing a lot of features. The real problem though is `tree-sitter`, which is currently fundamental to our syntax highlighting and diagnostic reporting, and is not easy to compile into WASM.
2. **Check on startup if the language server is installed, and if not, pull it and compile it automatically**
  - Pros:
    1. Easy implementation
    2. Easy distribution
    3. Updating the LS is somewhat easy (just check for updates on every startup)
  - Cons:
    1. Requires the user to have the Rust toolchain installed
    2. Takes a while (not much) to compile, diminishes user experience
3. **Check on startup if the language server is installed, and if not, pull a precompiled binary and install it automatically**
  - Pros:
    1. Easy distribution
    2. Easy updates
    3. Does not require users to have the Rust toolchain installed
  - Cons:
    1. Hard to implement
      - Requires us to publish binaries to MacOS, Linux, Windows on arm64 and x86-64, with a total of 6 binaries
      - We will need to develop a few build and testing systems to get this working
4. **Tell users to run `cargo install bend-language-server`**
  - Pros:
    1. Very easy to implement (we don't implement anything!)
    2. Allows users to use any version of the LS they want
      - This is not really important at this stage of Bend's development, since it still is very early
  - Cons:
    1. Terrible user experience
    4. No way to guarantee updates

I am currently trying to get option 1 working.

**Comment by kings177** [comment]
### Update
As explained above by edusporto, `Solution 1` didn't work, so we have decided to proceed with `Solution 2`:

> 2. Check on startup if the language server is installed, and if not, pull it and compile it automatically
> - Pros:
>   - Easy implementation
>   - Easy distribution
>   - Updating the LS is somewhat easy (just check for updates on every startup)
> - Cons:
>   - Requires the user to have the Rust toolchain installed
>   - Takes a while (not much) to compile, diminishes user experience

Regarding the Visual Studio Code extension, the plan is to release an MVP focusing on Debian-based and Darwin-based (MacOS) operating systems. full support for windows will be added in subsequent updates as we refine the cross-platform functionality.

**Comment by edusporto** [comment]
Finished implementing solution 2 on commit 0f4a173.
It works well on my MacOS machine and should probably work on Windows (at least with WSL enabled).
Eventually we should add an automated test suite.
